In [96]:
import netCDF4 as nc
import numpy as np

In [97]:
filepath = 'ME4OH_EN411_OFAM3/data/en4.1.1/1993-2014/ofam3-jra55.all.EN.4.1.1.f.profiles.g10.199301.update.extra.anom.199301_201412.nc'
file2read = nc.Dataset(filepath,'r')
print(file2read.variables)

{'en4_lat': <class 'netCDF4.Variable'>
float32 en4_lat(number_of_profile)
    units: degree North
unlimited dimensions: 
current shape = (10033,)
filling on, default _FillValue of 9.969209968386869e+36 used, 'en4_lon': <class 'netCDF4.Variable'>
float32 en4_lon(number_of_profile)
    units: degree East
unlimited dimensions: 
current shape = (10033,)
filling on, default _FillValue of 9.969209968386869e+36 used, 'en4_ymd': <class 'netCDF4.Variable'>
float32 en4_ymd(number_of_profile, ymd)
    units: [year month day-of-month]
unlimited dimensions: 
current shape = (10033, 3)
filling on, default _FillValue of 9.969209968386869e+36 used, 'en4_ydec': <class 'netCDF4.Variable'>
float32 en4_ydec(number_of_profile)
    units: decimal year
unlimited dimensions: 
current shape = (10033,)
filling on, default _FillValue of 9.969209968386869e+36 used, 'en4_maxdepth': <class 'netCDF4.Variable'>
float32 en4_maxdepth(number_of_profile)
    units: m
unlimited dimensions: 
current shape = (10033,)
fillin

In [98]:
lat = file2read["ts_lat"][:].data  # Latitude
long = file2read["ts_lon"][:].data  # Longitude
time = file2read["en4_ymd"][:].data  # Year , month , day for
mask = file2read["dohc_mask_by_en4_maxdepth"][:].data # Valid profile mask
dohc1 = file2read["dohc"][:, 0].data  # Layer 1 OHC anomaly target (NOTE: index 0 in python, index 1 in R)
salt = file2read["salt"][:].data  # Salinity

In [99]:
dohc1

array([0.3428138 , 0.34306267, 0.34290227, ...,        nan,        nan,
              nan], shape=(10033,), dtype=float32)

In [100]:
filtered_dohc1 = np.array([dohc1[idx] for idx in range(len(mask)) if mask[idx, 0] == 1])
filtered_dohc1

array([0.34489688, 0.34419084, 0.34414536, ..., 0.34756175,        nan,
              nan], shape=(6789,), dtype=float32)

In [80]:
dohc1_temp = file2read["dohc"][:, 0].data
dohc1_temp

array([0.3428138 , 0.34306267, 0.34290227, ...,        nan,        nan,
              nan], shape=(10033,), dtype=float32)

In [35]:
ds = nc.Dataset(filepath)


# Display some information about the dataset
print("Dimensions:")
for dim in ds.dimensions:
  print(dim, '=', ds.dimensions[dim])
  
print("Variables")
for key in ds.variables.keys():
  var = ds.variables[key]
  print("name =", key)
  print(" dims =", var.dimensions)
  print(" shape =", var.shape)
  print(" size =", var.size)
  print(" ndim =", var.ndim)
  print(" datatype =", var.datatype)

Dimensions:
number_of_profile = "<class 'netCDF4.Dimension'>": name = 'number_of_profile', size = 10033
ymd = "<class 'netCDF4.Dimension'>": name = 'ymd', size = 3
level = "<class 'netCDF4.Dimension'>": name = 'level', size = 51
level_bound = "<class 'netCDF4.Dimension'>": name = 'level_bound', size = 3
nv = "<class 'netCDF4.Dimension'>": name = 'nv', size = 2
string2 = "<class 'netCDF4.Dimension'>": name = 'string2', size = 2
string4 = "<class 'netCDF4.Dimension'>": name = 'string4', size = 4
string8 = "<class 'netCDF4.Dimension'>": name = 'string8', size = 8
string64 = "<class 'netCDF4.Dimension'>": name = 'string64', size = 64
Variables
name = en4_lat
 dims = ('number_of_profile',)
 shape = (10033,)
 size = 10033
 ndim = 1
 datatype = float32
name = en4_lon
 dims = ('number_of_profile',)
 shape = (10033,)
 size = 10033
 ndim = 1
 datatype = float32
name = en4_ymd
 dims = ('number_of_profile', 'ymd')
 shape = (10033, 3)
 size = 30099
 ndim = 2
 datatype = float32
name = en4_ydec
 dim